# Generated by Django 4.1.3 on 2022-11-26 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('availability_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['course', 'year', 'month', 'day'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
                ('course_intro', models.TextField(max_length=5000)),
            ],
            options={
                'ordering': ['style', 'course_name'],
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('day_id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('learner_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('disambiguator', models.CharField(blank=True, default='', max_length=45)),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'disambiguator'],
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('month_id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ['month'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('registration_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['availability', 'learner'],
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('style_id', models.AutoField(primary_key=True, serialize=False)),
                ('style_name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['style_name'],
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('year_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ['year'],
            },
        ),
        migrations.AddConstraint(
            model_name='style',
            constraint=models.UniqueConstraint(fields=('style_name',), name='unique_style'),
        ),
        migrations.AddField(
            model_name='registration',
            name='availability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='core.availability'),
        ),
        migrations.AddField(
            model_name='registration',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='core.learner'),
        ),
        migrations.AddConstraint(
            model_name='learner',
            constraint=models.UniqueConstraint(fields=('last_name', 'first_name', 'disambiguator'), name='unique_learner'),
        ),
        migrations.AddField(
            model_name='course',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='core.style'),
        ),
        migrations.AddField(
            model_name='availability',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='availabilities', to='core.course'),
        ),
        migrations.AddField(
            model_name='availability',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dates', to='core.day'),
        ),
        migrations.AddField(
            model_name='availability',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dates', to='core.month'),
        ),
        migrations.AddField(
            model_name='availability',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dates', to='core.year'),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('availability', 'learner'), name='unique_registration'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('style', 'course_name'), name='unique_course'),
        ),
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.UniqueConstraint(fields=('course', 'year', 'month', 'day'), name='unique_availability'),
        ),
    ]
